VIEW
CREATE VIEW vw_conceito_enade_faixa_por_curso AS SELECT 
  CASE 
    WHEN CONCEITO_ENADE >= 0 AND CONCEITO_ENADE < 0.945 THEN 1
    WHEN CONCEITO_ENADE >= 0.945 AND CONCEITO_ENADE < 1.945 THEN 2
    WHEN CONCEITO_ENADE >= 1.945 AND CONCEITO_ENADE < 2.945 THEN 3
    WHEN CONCEITO_ENADE >= 2.945 AND CONCEITO_ENADE < 3.945 THEN 4
    WHEN CONCEITO_ENADE >= 3.945 AND CONCEITO_ENADE <= 5 THEN 5
  END AS CONCEITO_ENADE_FAIXA,
  COD_CURSO,
  COD_INSTITUICAO
FROM 
  CURSO 
  WHERE CONCEITO_ENADE IS NOT NULL;
