SELECT 
  CONCEITO_ENADE_FAIXA, 
  ROUND(
    AVG(PERCENTUAL_DOCENTES_MESTRADO), 
    2
  ) AS MEDIA_PERCENTUAL_DOCENTES_MESTRADO, 
  ROUND(
    AVG(PERCENTUAL_DOCENTES_DOUTORADO), 
    2
  ) AS MEDIA_PERCENTUAL_DOCENTES_DOUTORADO, 
  ROUND(
    AVG(PERCENTUAL_DOCENTES_MESTRADO) + AVG(PERCENTUAL_DOCENTES_DOUTORADO), 
    2
  ) AS PERCENTUAL_DOCENTES_TOTAL 
FROM 
  INSTITUICAO I 
  JOIN vw_conceito_enade_faixa_por_curso C ON C.COD_INSTITUICAO = I.COD_INSTITUICAO 
GROUP BY 
  CONCEITO_ENADE_FAIXA 
ORDER BY 
  CONCEITO_ENADE_FAIXA;
