SELECT 
  AVG(CONCEITO_ENADE) as MEDIA_ENADE, 
  CATEGORIA, 
  MODALIDADE 
FROM 
  INSTITUICAO I 
  JOIN CURSO C ON C.COD_INSTITUICAO = I.COD_INSTITUICAO 
WHERE 
  CONCEITO_ENADE IS NOT NULL 
GROUP BY 
  CATEGORIA, 
  MODALIDADE;
