SELECT 
  COUNT(*) AS NUM_CURSOS, 
  UF 
FROM 
  MUNICIPIO M 
  JOIN MUNICIPIO_has_CURSO MC ON MC.MUNICIPIO_COD_MUNICIPIO = M.COD_MUNICIPIO 
  JOIN CURSO C ON C.COD_CURSO = MC.CURSO_COD_CURSO 
WHERE 
  C.SITUACAO = 'Em atividade' 
GROUP BY 
  UF 
ORDER BY 
  1 DESC;
